# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-09-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180129_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
